### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by dafemec** [xamarin/Xamarin.Forms-api-docs#156]
How do you use this?  An example would certainly help!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a7f03f5-06cc-104d-894f-f0a646f94295
* Version Independent ID: 6bf60215-59b2-7aba-60d6-79a200b5e240
* Content: [IMenuItemController.IsEnabled Property (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.imenuitemcontroller.isenabled?view=xamarin-forms#Xamarin_Forms_IMenuItemController_IsEnabled)
* Content Source: [docs/Xamarin.Forms/IMenuItemController.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/IMenuItemController.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by hartez** [comment]
> How do you use this? An example would certainly help!

@dafemec Generally speaking, you _don't_ use this - that's why the description says "For internal use by platform renderers." But if you are looking for examples of enabling/disabling a MenuItem at runtime, you can find them [here](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/menuitem#enable-or-disable-a-menuitem-at-runtime).
