### ISSUE TITLE
Markdown formatting broken in ScrollView Remarks

### ISSUE THREAD

**Issue by hartez** [xamarin/Xamarin.Forms-api-docs#285]
The markdown formatting for the C# example on https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.scrollview?view=xamarin-forms#remarks is formatting incorrectly.

![image](https://user-images.githubusercontent.com/538025/124987456-21fd5280-dffa-11eb-8a70-37a81b79bad9.png)

**Comment by davidbritch** [comment]
I just discovered this on multiple Forms API docs so came to the repo to see if anyone else had noticed it. The content hasn't been published since last year, so this will be due to a back-end change.

Interestingly, the build system tells me that I made a config change on 16th June this year, when I didn't. That also signals a back-end change.

I'll follow up with the team in China.

**Comment by davidbritch** [comment]
I've logged a bug with the docs engineering team.

**Comment by davidbritch** [comment]
This is fixed!
